//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warbler.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Syntax {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Syntax() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warbler.Resources.Errors.Syntax", typeof(Syntax).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character &apos; at end of input.
        /// </summary>
        internal static string ApostropheAtEof {
            get {
                return ResourceManager.GetString("ApostropheAtEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty character literal at position {0}.
        /// </summary>
        internal static string EmptyChar {
            get {
                return ResourceManager.GetString("EmptyChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a =.
        /// </summary>
        internal static string ExpectedAssignment {
            get {
                return ResourceManager.GetString("ExpectedAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a ) after function arguments.
        /// </summary>
        internal static string ExpectedClosingArgsBracket {
            get {
                return ResourceManager.GetString("ExpectedClosingArgsBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a ) after an expression.
        /// </summary>
        internal static string ExpectedClosingBracket {
            get {
                return ResourceManager.GetString("ExpectedClosingBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a ) after function paramters.
        /// </summary>
        internal static string ExpectedClosingParamsBracket {
            get {
                return ResourceManager.GetString("ExpectedClosingParamsBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a :.
        /// </summary>
        internal static string ExpectedColon {
            get {
                return ResourceManager.GetString("ExpectedColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression.
        /// </summary>
        internal static string ExpectedExpression {
            get {
                return ResourceManager.GetString("ExpectedExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an identifier.
        /// </summary>
        internal static string ExpectedIdentifier {
            get {
                return ResourceManager.GetString("ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a (.
        /// </summary>
        internal static string ExpectedOpeningBracket {
            get {
                return ResourceManager.GetString("ExpectedOpeningBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a parameter name.
        /// </summary>
        internal static string ExpectedParameterName {
            get {
                return ResourceManager.GetString("ExpectedParameterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a parameter type.
        /// </summary>
        internal static string ExpectedParameterType {
            get {
                return ResourceManager.GetString("ExpectedParameterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a return type.
        /// </summary>
        internal static string ExpectedReturnType {
            get {
                return ResourceManager.GetString("ExpectedReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid assignment target.
        /// </summary>
        internal static string InvalidAssignmentTarget {
            get {
                return ResourceManager.GetString("InvalidAssignmentTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected character {0} at position {1}.
        /// </summary>
        internal static string UnexpectedChar {
            get {
                return ResourceManager.GetString("UnexpectedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected token {0}.
        /// </summary>
        internal static string UnexpectedToken {
            get {
                return ResourceManager.GetString("UnexpectedToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown escape sequence at position {0}.
        /// </summary>
        internal static string UnknownEscape {
            get {
                return ResourceManager.GetString("UnknownEscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a closing &lt;: after block.
        /// </summary>
        internal static string UnterminatedBlock {
            get {
                return ResourceManager.GetString("UnterminatedBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a closing &apos; at position {0}.
        /// </summary>
        internal static string UnterminatedChar {
            get {
                return ResourceManager.GetString("UnterminatedChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected a &quot; at position {0}.
        /// </summary>
        internal static string UnterminatedString {
            get {
                return ResourceManager.GetString("UnterminatedString", resourceCulture);
            }
        }
    }
}
