//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warbler.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Type {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Type() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warbler.Resources.Errors.Type", typeof(Type).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare expressions of types {0} and {1}.
        /// </summary>
        internal static string ComparisonOperandsMismatch {
            get {
                return ResourceManager.GetString("ComparisonOperandsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional expression branches must have the same type.
        /// </summary>
        internal static string ConditionBranchesMismatch {
            get {
                return ResourceManager.GetString("ConditionBranchesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;!&apos; operator can only be used with Boolean expressions.
        /// </summary>
        internal static string NegateNonBoolean {
            get {
                return ResourceManager.GetString("NegateNonBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;-&apos; operator can only be used with Double or Integer expressions.
        /// </summary>
        internal static string NegateNonNumeric {
            get {
                return ResourceManager.GetString("NegateNonNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A ternary condition must be Boolean.
        /// </summary>
        internal static string NonBooleanCondition {
            get {
                return ResourceManager.GetString("NonBooleanCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Both operands must be either Integer or Double.
        /// </summary>
        internal static string NonNumericBinaryOperands {
            get {
                return ResourceManager.GetString("NonNumericBinaryOperands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;++&apos; operator can only be used with expressions of type String.
        /// </summary>
        internal static string NonStringConcatenation {
            get {
                return ResourceManager.GetString("NonStringConcatenation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ternary branches must have the same type.
        /// </summary>
        internal static string TernaryBranchesMismatch {
            get {
                return ResourceManager.GetString("TernaryBranchesMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression of type {0}.
        /// </summary>
        internal static string VariableAssignmentMismatch {
            get {
                return ResourceManager.GetString("VariableAssignmentMismatch", resourceCulture);
            }
        }
    }
}
